# Utilisez l'image de base Python
FROM python:3.8-slim-buster

ENV MONGO_DB_USERNAME=root\
    MONGO_DB__PWD=example

# Répertoire de travail dans le conteneur
WORKDIR /client_rest

COPY client_rest/requirements.txt /client_rest/

# Installez les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposez le port 5000
EXPOSE 5000

VOLUME [ "/client_rest" ]

# Commande pour exécuter l'application
CMD [ "python3", "client.py" ]